Add example for Array.flatMap()
mdn/interactive-examples pull request #1697
Opened 2020-10-04 01:29 UTC by talitaoliveira

Pull Request for issue #1587

2020-10-06 13:54 UTC, krankj commented on live-examples/js-examples/array/array-flatmap.js
> +    nome: 'Human 2',
typo "nome"

2020-10-07 01:31 UTC, talitaoliveira commented on live-examples/js-examples/array/array-flatmap.js
> +    nome: 'Human 2',
Sorry! Fixed it.

2020-10-14 12:28 UTC, velusgautam requested changes
Just a suggestion
Can you give some more simple dataset example to show the flatmap process. It first map() and then it flat() to one level deep. 

const nums = [1,2, [3], [4],[] ];
const flattened = nums.flatMap(num => num);
// [ 1, 2, 3, 4 ]

2020-10-23 20:55 UTC, talitaoliveira commented
Hey @velusgautam . Done with your suggestion.
I think that's valid, but when I made the first example the intention was to be more a "real life example".
But that's ok. :)

2020-10-24 10:32 UTC, chrisdavidmills commented
This is looking pretty good, thanks @talitaoliveira ! It looks like a bunch of rogue commits have ended up in this PR though; I'm assuming you didn't touch 16 files. A rebase against latest origin would probably fix this?

2020-10-24 12:10 UTC, talitaoliveira commented
Yeah I didn't touch them. Probably I did something wrong when getting the changes from the origin.
Now I guess it's right...

2021-05-30 17:57 UTC, tannerdolby commented
@wbamberg Is this PR still under review or has it become stale? I have an Array.flatMap() interactive example spun up in my local `mdn/interactive-examples` repo if you want me to submit that as a fresh PR. Let me know!

2021-06-06 01:59 UTC, wbamberg commented
> @wbamberg Is this PR still under review or has it become stale? I have an Array.flatMap() interactive example spun up in my local `mdn/interactive-examples` repo if you want me to submit that as a fresh PR. Let me know!

@tannerdolby , this PR still seems to have lots of extra changes in it, so yes, please do submit a new one. Thanks!

2022-06-07 16:15 UTC, Rumyra commented
Closing this pr due to it being superseeded by https://github.com/mdn/interactive-examples/pull/1845

2022-06-07 16:15 UTC, closed without merging