Clarify example. Closes #1622
mdn/interactive-examples pull request #1781
Opened 2021-03-18 10:14 UTC by hinell

More details at #1622

2021-03-30 11:45 UTC, velusgautam commented on live-examples/js-examples/object/object-prototype-isprototypeof.js
> -// expected output: true
Why you deleted expected outputs?

2021-05-06 16:31 UTC, wbamberg requested changes
Thanks @hinell . I like this change but it should have an `// expected output` line for both `console.log()` statements.

2021-05-06 16:31 UTC, wbamberg commented on live-examples/js-examples/object/object-prototype-isprototypeof.js
> +console.log(Foo.prototype.isPrototypeOf(bar));
This should have:

```
 // expected output: true
```

after it

2021-05-12 17:54 UTC, wbamberg approved these changes
Thanks @hinell !

2021-05-12 17:54 UTC, merged