Focus, hover, active
mdn/interactive-examples pull request #2179
Opened 2022-06-12 13:16 UTC by NiedziolkaMichal

Those are interactive examples for pseudo-classes [:focus](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus), [:focus-visible](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible), [:focus-within](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within), [:hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover), [:active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active).

![image](https://user-images.githubusercontent.com/100634371/173235010-6ffe6d4d-267c-41c6-8f09-be5ce67b0e8d.png)

![image](https://user-images.githubusercontent.com/100634371/173235029-b4ebf1f4-34b3-4a71-b637-6cb3162d2f38.png)

![image](https://user-images.githubusercontent.com/100634371/173235035-85e63fba-5ce1-4660-bb84-eb6e2222471f.png)

![image](https://user-images.githubusercontent.com/100634371/173235043-fa91b207-2b7f-4ce1-bd4c-b052e782f0b0.png)

![image](https://user-images.githubusercontent.com/100634371/173235051-ac93601d-5aab-491d-9e58-7c270e05bcb5.png)

2022-06-30 03:39 UTC, wbamberg requested changes
These work great and are fine examples, but asking for gender should not offer only Male/Female. See for example: https://www.ruth-ng.co.uk/how-to-ask-about-gender-in-forms-respectfully . 

Maybe consider something silly instead, like favourite flavor of ice cream?

2022-06-30 03:39 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/hover.css
> +}
Maybe consider better contrast for the button text and background?

2022-06-30 15:31 UTC, NiedziolkaMichal commented
@wbamberg I have changed Gender to Flavor as requested, also contrast of :hover was improved.

Thank you for reviewing.

2022-07-01 16:50 UTC, wbamberg approved these changes
👍 thank you @NiedziolkaMichal !

2022-07-01 16:50 UTC, merged