enabled, disabled, in-range, out-of-range, optional, required
mdn/interactive-examples pull request #2187
Opened 2022-06-16 11:20 UTC by NiedziolkaMichal

Those are interactive examples for pseudo-classes [:enabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled), [:disabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled), [:in-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:in-range), [:out-of-range](https://developer.mozilla.org/en-US/docs/Web/CSS/:out-of-range), [:optional](https://developer.mozilla.org/en-US/docs/Web/CSS/:optional), [:required](https://developer.mozilla.org/en-US/docs/Web/CSS/:required).

![image](https://user-images.githubusercontent.com/100634371/174059008-49402fed-8349-459d-9c27-0497d08266ff.png)

![image](https://user-images.githubusercontent.com/100634371/174059044-ad1e7922-0c4c-47a9-85ed-8abe2cd5bfe5.png)

![image](https://user-images.githubusercontent.com/100634371/174059069-e2a0feae-9bfa-4a1c-a6a4-7266b7891b95.png)

![image](https://user-images.githubusercontent.com/100634371/174059089-a7380892-b99d-4a13-a38a-fb2cb2688b24.png)

![image](https://user-images.githubusercontent.com/100634371/174059124-e2480ff7-8e21-4032-91d4-828fe8367b5d.png)

![image](https://user-images.githubusercontent.com/100634371/174059154-a0f94d13-7d16-42cb-b6a1-55fbea077236.png)

2022-07-02 00:21 UTC, wbamberg requested changes
Thank you @NiedziolkaMichal ! Most of my comments are to make sure the editor is tall enough to fit the HTML. And one contrast issue.

2022-07-02 00:21 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/meta.json
> +            "height": "tabbed-shorter"
```suggestion
            "height": "tabbed-standard"
```

(the HTML overflows)

2022-07-02 00:21 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/meta.json
> +            "height": "tabbed-shorter"
```suggestion
            "height": "tabbed-standard"
```

(the HTML overflows)

2022-07-02 00:21 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/meta.json
> +            "height": "tabbed-shorter"
```suggestion
            "height": "tabbed-standard"
```

(the HTML overflows)

2022-07-02 00:21 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/meta.json
> +            "height": "tabbed-shorter"
```suggestion
            "height": "tabbed-standard"
```

(the HTML overflows)

2022-07-02 00:21 UTC, wbamberg commented on live-examples/css-examples/pseudo-class/disabled.css
> +    background-color: indianred;
This makes the text really hard to read. Choose a different colour perhaps?

2022-07-05 10:09 UTC, NiedziolkaMichal commented
I have updated colors in example disabled. Is that ok?
![image](https://user-images.githubusercontent.com/100634371/177304735-3dbd4ec1-0727-465c-9901-c5780ca761e7.png)

2022-07-26 21:16 UTC, NiedziolkaMichal commented
I also added html attribute [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).

2022-08-31 00:59 UTC, wbamberg approved these changes
👍 thank you!

2022-08-31 01:12 UTC, wbamberg commented
CI failure was not you, it was caused by https://github.com/mdn/interactive-examples/commit/c6b5dc61c6b558c58091b8d974e752e64fc040d2 - I'll make a separate fix.

2022-08-31 01:12 UTC, merged