Add an example for BigInt64Array()
mdn/interactive-examples pull request #2411
Opened 2023-01-17 23:57 UTC by MrBrain295

### Description
Add an example for BigInt64Array().

### Motivation
There isn't already an example.

### Additional details

### Related issues and pull requests

2023-01-18 16:42 UTC, NiedziolkaMichal requested changes
Thanks for filing the pull request. I think it would be better if the following changes were made:
- You need to fix the warnings to pass ESLint
- Since it's an example showing the general functionality of `BigInt64Array`, it should show multiple different features
- Each `console.log` should have a `// Expected Output: <output_here>` comment below
- Other examples use the name `uint8`, so I think the most appropriate variable name would be `bigint64` here
- Try to keep the example as concise as possible.

2023-01-30 23:22 UTC, Josh-Cena reviewed
I don't know if the `BigInt()` usage is intentional, but I suggest we show something that doesn't lose precision.

2023-01-30 23:22 UTC, Josh-Cena commented on live-examples/js-examples/bigint/bigint64.js
> +bigint64[4] = BigInt(3337090060496542);
```suggestion
bigint64[0] = 5886014448488689n;
bigint64[1] = 1881938909131133n;
bigint64[2] = 1898875537769492n;
bigint64[3] = 2156704815705747n;
bigint64[4] = 3337090060496542n;
```

(Number literals already lose precision)

2023-01-30 23:22 UTC, Josh-Cena commented on live-examples/js-examples/bigint/bigint64.js
> +bigint64[0] = BigInt(6118793953620967);
```suggestion
bigint64[0] = 6118793953620967n;
```

2023-01-30 23:22 UTC, Josh-Cena commented on live-examples/js-examples/bigint/bigint64.js
> +console.log(bigint64); //Expected Output: BigInt64Array [6118793953620967n, 1881938909131133n, 1898875537769492n, 2156704815705747n, 3337090060496542n]
Update the output here; also there needs to be a space after `//`

2023-02-07 16:14 UTC, MrBrain295 commented
@Josh-Cena can you please re-review?

2023-02-08 15:20 UTC, Josh-Cena reviewed
LGTM modulo one change. Waiting for @NiedziolkaMichal for the approval

2023-02-08 15:20 UTC, Josh-Cena commented on live-examples/js-examples/bigint/bigint64.js
> +bigint64.set([BigInt(100), BigInt(200)], 1);
```suggestion
bigint64.set([100n, 200n], 1);
```

2023-02-08 17:36 UTC, MrBrain295 commented
@NiedziolkaMichal could you please review?

2023-02-09 15:22 UTC, NiedziolkaMichal submitted a review, later dismissed
- You need to fix the warnings to pass ESLint
- There are 4 scrollbars because of too long output:
![image](https://user-images.githubusercontent.com/100634371/217854439-97810483-e6f2-4d44-b5e8-5dfdb8f9bbd6.png)
- We always place `// Expected Output` in the line under `console.log` and we typically place an empty line under it
- Try to keep the example as concise as possible

2023-02-09 21:47 UTC, MrBrain295 commented
How do I fix the 'BigInt64Array' is not defined error

2023-02-10 11:24 UTC, NiedziolkaMichal commented
It needs to be added to `globals` in [.eslintrc](https://github.com/mdn/interactive-examples/blob/main/.eslintrc)

2023-02-10 16:04 UTC, MrBrain295 commented
I don’t have much eslint experience so could you please explain how to do that?

2023-02-10 16:25 UTC, MrBrain295 commented
@NiedziolkaMichal I can't figure out why the test is failing but I did get eslint to work.

2023-02-10 21:51 UTC, caugner commented
@NiedziolkaMichal @MrBrain295 I'm very sorry about the failing workflow. https://github.com/mdn/interactive-examples/pull/2429 should resolve it.

2023-02-16 16:37 UTC, NiedziolkaMichal commented
@MrBrain295 I have added PR #2439 which should resolve this problem. Could you still take a look into other problems with the example that I mentioned? I have also noticed that you have placed the new example into a new directory called `bigint`. I think it would be better to place it in `typedarray` together with other related examples.

2023-08-02 14:47 UTC, queengooborg commented
Thanks @MrBrain295 for your hard work on this -- since this PR has been idling for a while, I made the requested changes!

2023-08-02 15:06 UTC, queengooborg approved these changes, later dismissed

2023-08-02 15:19 UTC, queengooborg commented
Okay, _now_ this should be ready for re-review!

2023-08-23 10:36 UTC, bsmth approved these changes
Thanks all, this looks good to me, merging shortly:

<details>

![image](https://github.com/mdn/interactive-examples/assets/43580235/9a87e24e-76f8-4099-839a-da49064a08e9)

</details>

2023-08-23 10:37 UTC, merged