Adding an example for overscroll-behavior-x
mdn/interactive-examples pull request #2442
Opened 2023-02-20 03:29 UTC by doanaminh

### Description
Added another dimension to the existing overscroll-behavior example.
Isolated only the x-axis to emphasize that the overscroll-behavior property should only work in one dimension.

### Motivation
Created an example with 2 dimensions to visually emphasize the effects of overscroll-behavior-x.

### Additional details
There was not an existing example. 

 

### Related issues and pull requests

2023-02-20 12:57 UTC, NiedziolkaMichal requested changes
Thanks a lot for this example, it looks good. I have added some comments about how I think it could be improved.

2023-02-20 12:57 UTC, NiedziolkaMichal commented on live-examples/css-examples/basic-box-model/overscroll-behavior-x.html
> +<section id="example-choice-list" class="example-choice-list large" data-property="overscroll-behavior">
Attribute `data-property` should have a value `overscroll-behavior-x`.

2023-02-20 12:57 UTC, NiedziolkaMichal commented on live-examples/css-examples/basic-box-model/overscroll-behavior-x.html
> +                    This is sample text to fill up space. Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius veniam, animi laudantium quibusdam vitae cumque officiis in eos laborum molesti
This paragraph is way too long, it takes forever to scroll through it on the phone. Also visible content of the box should indicate that there is some additional content on the right. On many devices, scrollbar is not shown until scrolling through the content, so users can easily think that there is more text only at the bottom:
![image](https://user-images.githubusercontent.com/100634371/220114034-b78a82b2-ea48-4510-819e-1c61ee072e81.png)

2023-02-20 12:57 UTC, NiedziolkaMichal commented on live-examples/css-examples/basic-box-model/overscroll-behavior-x.html
> +                This is just some sample text. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eum at aut eius aliquam blanditiis itaque unde reiciendis? Maxime obcaecati possimus dicta qui
I think most of this text is unnecessary. It's good to allow users to scroll through the content horizontally and vertically, so they can see how CSS property affects both axes, but a single short sentence would be enough to achieve this.

2023-02-22 20:54 UTC, doanaminh reviewed
Made changes as requested by @sideshowbarker.

2023-02-23 22:53 UTC, doanaminh reviewed
Completed changes required to pass checks.

2023-02-25 19:05 UTC, doanaminh reviewed
3rd attempt at getting changes fixed and rebasing the branch to get ready to merge.

2023-02-26 22:14 UTC, NiedziolkaMichal commented
It looks good :) Just fix those two eslint errors and we can merge:
```
live-examples/css-examples/basic-box-model/overscroll-behavior-x.css
 46:2  ✖  Delete "·"                            prettier/prettier
 46:2  ✖  Unexpected whitespace at end of line  no-eol-whitespace
```

2023-02-28 00:05 UTC, doanaminh commented
Okay, I deleted the whitespace so hopefully, it can merge this time!

2023-02-28 15:10 UTC, NiedziolkaMichal approved these changes

2023-02-28 15:10 UTC, merged

2023-02-28 15:11 UTC, NiedziolkaMichal commented
Thank you for your contribution, everything looks good.