docs: update `pseudo-class` child examples
mdn/interactive-examples pull request #2622
Opened 2023-09-26 08:22 UTC by hamirmahal

fixes #2616.

2023-09-26 08:23 UTC, hamirmahal commented
![image](https://github.com/mdn/interactive-examples/assets/43425812/e118ed0a-40d0-4247-b21f-8eb19f503fb2)

2023-09-26 08:23 UTC, hamirmahal commented
![image](https://github.com/mdn/interactive-examples/assets/43425812/40e2ff21-670d-4470-bea2-91ad21449622)

2023-09-26 08:23 UTC, hamirmahal commented
![image](https://github.com/mdn/interactive-examples/assets/43425812/f4e0ea1d-1cd7-4258-a122-362ec0d1595b)

2023-09-26 08:30 UTC, hamirmahal commented
![image](https://github.com/mdn/interactive-examples/assets/43425812/1b72f7c0-3374-4a44-94ae-6502edbfa77f)

2023-09-27 16:44 UTC, estelle approved these changes
Thank you!

2023-09-27 16:44 UTC, estelle commented on live-examples/css-examples/pseudo-class/first-child.html
> +<p>Accomplished athletes:</p>
```suggestion
<p>Track &amp; field champions:</p>
```

2023-09-27 16:44 UTC, estelle commented on live-examples/css-examples/pseudo-class/last-child.html
> +<p>Accomplished athletes:</p>
```suggestion
<p>Track &amp; field champions:</p>
```

2023-09-27 16:44 UTC, estelle commented on live-examples/css-examples/pseudo-class/nth-child.html
> +<p>Accomplished athletes:</p>
```suggestion
<p>Track &amp; field champions:</p>
```

2023-09-27 17:47 UTC, wbamberg approved these changes

2023-09-28 17:09 UTC, dipikabh requested changes, later dismissed
making a tiny change to test retriggering the build job

2023-09-28 17:09 UTC, dipikabh commented on live-examples/css-examples/pseudo-class/first-child.html
> +<p>Track &amp; field champions:</p>
```suggestion
<p>Track &amp; field champions:</p>

```

2023-09-28 17:16 UTC, dipikabh submitted a review, later dismissed

2023-09-28 17:16 UTC, dipikabh commented on live-examples/css-examples/pseudo-class/first-child.html
> +
```suggestion
```

2023-09-28 17:44 UTC, merged